steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'web-server'
  - '--image'
  - 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--set-secrets="BATCH_AUTH_TOKEN=BATCH_AUTH_TOKEN:1"'
  - '--set-secrets="NEXTAUTH_SECRET=NEXTAUTH_SECRET:1"'
  - '--set-secrets="NEXTAUTH_URL=NEXTAUTH_URL:1"'
  - '--set-secrets="SLACK_BOT_TOKEN=SLACK_BOT_TOKEN:1"'
  - '--set-secrets="SLACK_CLIENT_ID=SLACK_CLIENT_ID:1"'
  - '--set-secrets="SLACK_CLIENT_SECRET=SLACK_CLIENT_SECRET:1"'
images:
- 'gcr.io/$PROJECT_ID/web-server:$COMMIT_SHA'